WITH TARGET_NODE AS(
        SELECT *
        FROM firstedge
        WHERE firstedge.NODE_ID = 3300000000113702
    ),
    NEIBOUR_NODE AS(
        SELECT HAS_CREATOR_ID AS NEI_ID,'HAS_CREATOR_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT IS_LOCATED_IN_ID AS NEI_ID,'IS_LOCATED_IN_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT REPLY_OF_ID AS NEI_ID,'REPLY_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT CONTAINER_OF_ID AS NEI_ID,'CONTAINER_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT HAS_MEMBER_ID AS NEI_ID,'HAS_MEMBER_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT HAS_MODERATOR_ID AS NEI_ID,'HAS_MODERATOR_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT HAS_TAG_ID AS NEI_ID ,'HAS_TAG_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT HAS_INTEREST_ID AS NEI_ID,'HAS_INTEREST_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT KNOWS_ID AS NEI_ID,'KNOWS_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT LIKES_ID AS NEI_ID,'LIKES_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT IS_PART_OF_ID AS NEI_ID,'IS_PART_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT IS_SUBCLASS_OF_ID AS NEI_ID,'IS_SUBCLASS_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT HAS_TYPE_ID AS NEI_ID,'HAS_TYPE_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT STUDY_AT_ID AS NEI_ID,'STUDY_AT_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT WORK_AT_ID AS NEI_ID,'WORK_AT_ID' AS 'EDGE_LABEL' FROM TARGET_NODE
    ),
    FS_JOIN AS (
        SELECT NEI_ID,EDGE_LABEL,ENDNODEID
        FROM NEIBOUR_NODE LEFT JOIN secondedge ON NEI_ID = VALUEID
    )
SELECT *
FROM vertex,FS_JOIN
WHERE vertex.NODE_ID = FS_JOIN.NEI_ID OR
vertex.NODE_ID = FS_JOIN.ENDNODEID;
