WITH TARGET_NODE AS(
        SELECT *
        FROM firstedge
        WHERE firstedge.NODE_ID = 3300000000113702
    ),
    NEIBOUR_NODE AS(
        SELECT HAS_CREATOR_ID AS NEI_ID,'CREATOR' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT IS_LOCATED_IN_ID AS NEI_ID,'LOCATION' AS 'EDGE_LABEL' FROM TARGET_NODE
        UNION ALL
        SELECT REPLY_OF_ID AS NEI_ID, 'REPLY' AS 'EDGE_LABEL' FROM TARGET_NODE
    )

SELECT *
FROM NEIBOUR_NODE;
