import vertica_python
import time


class VerticaDatabase(object):
    def __init__(self, host, user, database, password, port=5433):
        conn_info = {
            'host': host,
            'port': port,
            'user': user,
            'database': database,
            'password': password,
            # autogenerated session label by default,
            'session_label': 'some_label',
            # 10 minutes timeout on queries
            'read_timeout': 6000,
            # default throw error on invalid UTF-8 results
            'unicode_error': 'strict',
            # SSL is disabled by default
            'ssl': False,
            # using server-side prepared statements is disabled by default
            'use_prepared_statements': False,
            # connection timeout is not enabled by default
            'connection_timeout': 50
        }
        self.connection = vertica_python.connect(**conn_info)

    def close(self):
        self.connection.close()

    def getRelatedNode(self, keywords):
        # with self.connection as connection:
        cur = self.connection.cursor('dict')
        cur.execute("SELECT *"
                    "FROM vertex "
                    "WHERE ("
                    # "REGEXP_LILE(NODE_ID,'.*\\bchina\\b.*' ,'i') | "
                    "REGEXP_LIKE(NODE_LABEL, :keyword ,'i') or "
                    "REGEXP_LIKE(TYPE, :keyword ,'i') or "
                    "REGEXP_LIKE(FIRST_NAME, :keyword ,'i') or "
                    "REGEXP_LIKE(LAST_NAME, :keyword ,'i') or "
                    "REGEXP_LIKE(GENDER, :keyword ,'i') or "
                    "REGEXP_LIKE(EMAIL, :keyword ,'i') or "
                    "REGEXP_LIKE(SPEAKS, :keyword ,'i') or "
                    "REGEXP_LIKE(BROWSER_USED, :keyword ,'i') or "
                    "REGEXP_LIKE(LOCATION_IP, :keyword ,'i') or "
                    "REGEXP_LIKE(NAME, :keyword ,'i') or "
                    "REGEXP_LIKE(CONTENT, :keyword ,'i') or "
                    # "REGEXP_LILE(ID,'.*\\bchina\\b.*' ,'i') | "
                    "REGEXP_LIKE(LANGUAGE, :keyword ,'i') or "
                    "REGEXP_LIKE(IMAGE_FILE, :keyword ,'i') or "
                    "REGEXP_LIKE(TITLE, :keyword ,'i') or "
                    "REGEXP_LIKE(URL, :keyword ,'i')"
                    ");", {'keyword': ".*\\b" + str.strip(keywords) + "\\b.*"})
        result = cur.fetchall()
        return result

    def getNeighbourhood(self, ck):
        cur = self.connection.cursor('dict')
        cur.execute(
            "WITH TARGET_NODE AS("
            "SELECT * "
            "FROM firstedge "
            "WHERE firstedge.NODE_ID = :CK "
            "),"
            "NEIBOUR_NODE AS("
            "SELECT HAS_CREATOR_ID AS NEI_ID,'HAS_CREATOR_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT IS_LOCATED_IN_ID AS NEI_ID,'IS_LOCATED_IN_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT REPLY_OF_ID AS NEI_ID,'REPLY_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT CONTAINER_OF_ID AS NEI_ID,'CONTAINER_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT HAS_MEMBER_ID AS NEI_ID,'HAS_MEMBER_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT HAS_MODERATOR_ID AS NEI_ID,'HAS_MODERATOR_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT HAS_TAG_ID AS NEI_ID ,'HAS_TAG_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT HAS_INTEREST_ID AS NEI_ID,'HAS_INTEREST_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT KNOWS_ID AS NEI_ID,'KNOWS_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT LIKES_ID AS NEI_ID,'LIKES_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT IS_PART_OF_ID AS NEI_ID,'IS_PART_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT IS_SUBCLASS_OF_ID AS NEI_ID,'IS_SUBCLASS_OF_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT HAS_TYPE_ID AS NEI_ID,'HAS_TYPE_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT STUDY_AT_ID AS NEI_ID,'STUDY_AT_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "UNION ALL "
            "SELECT WORK_AT_ID AS NEI_ID,'WORK_AT_ID' AS 'EDGE_LABEL' FROM TARGET_NODE "
            "),"
            "FS_JOIN AS ("
            "SELECT NEI_ID,EDGE_LABEL,ENDNODEID "
            "FROM NEIBOUR_NODE LEFT JOIN secondedge ON NEI_ID = VALUEID "
            ")"
            "SELECT * "
            "FROM vertex,FS_JOIN "
            "WHERE vertex.NODE_ID = FS_JOIN.NEI_ID OR "
            "vertex.NODE_ID = FS_JOIN.ENDNODEID ;", {'CK': int(ck)}
        )
        result = cur.fetchall()
        return result

    def getNodeTime(self, keywords):
        total_time = 0.0
        start = time.time()
        result = self.getRelatedNode(keywords=keywords)
        # print(result.__len__())
        total_time = time.time() - start
        return total_time


    def getNeiTime(self,ck):
        total_time = 0.0
        start = time.time()
        result = self.getNeighbourhood(ck=ck)
        total_time = time.time() - start
        return total_time